[tool.poetry]
name = "repl_python3_pynotes"
version = "0.1.0"
description = ""
authors = ["sudosnugg <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
point = "^0.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
